// Auto-generated by scripts/codegen.py from config/protocol.yaml.
//
// 警告：本文件生成在 build 目录中，清理构建目录（rm -rf build、
// colcon build --cmake-clean-first 等）会连同 USER CODE 块中的手写代码一起丢失。
// 长期维护的 MCU 业务代码请保存在你的 MCU 工程里，本文件只做集成拷贝。
#include "protocol.h"
#include <string.h>

/* USER CODE BEGIN Includes */
/* USER CODE END Includes */

// 解析器状态定义
typedef enum
{
    STATE_WAIT_HEADER1,
    STATE_WAIT_HEADER2,
    STATE_WAIT_ID,
    STATE_WAIT_LEN,
    STATE_WAIT_DATA,
    STATE_WAIT_CRC
} State;

// 单包 payload 解析缓冲区 (最大结构体 payload=4, 最大 wire payload=4)
static State rx_state = STATE_WAIT_HEADER1;
static uint8_t rx_buffer[4];
static uint16_t rx_cnt = 0;
static uint8_t rx_data_len = 0;
static uint8_t rx_id = 0;
static uint8_t rx_checksum = 0;

// CRC8 查找表 (多项式 0x31)
static const uint8_t CRC8_TABLE[256] = {
    0x00,
    0x31,
    0x62,
    0x53,
    0xC4,
    0xF5,
    0xA6,
    0x97,
    0xB9,
    0x88,
    0xDB,
    0xEA,
    0x7D,
    0x4C,
    0x1F,
    0x2E,
    0x43,
    0x72,
    0x21,
    0x10,
    0x87,
    0xB6,
    0xE5,
    0xD4,
    0xFA,
    0xCB,
    0x98,
    0xA9,
    0x3E,
    0x0F,
    0x5C,
    0x6D,
    0x86,
    0xB7,
    0xE4,
    0xD5,
    0x42,
    0x73,
    0x20,
    0x11,
    0x3F,
    0x0E,
    0x5D,
    0x6C,
    0xFB,
    0xCA,
    0x99,
    0xA8,
    0xC5,
    0xF4,
    0xA7,
    0x96,
    0x01,
    0x30,
    0x63,
    0x52,
    0x7C,
    0x4D,
    0x1E,
    0x2F,
    0xB8,
    0x89,
    0xDA,
    0xEB,
    0x3D,
    0x0C,
    0x5F,
    0x6E,
    0xF9,
    0xC8,
    0x9B,
    0xAA,
    0x84,
    0xB5,
    0xE6,
    0xD7,
    0x40,
    0x71,
    0x22,
    0x13,
    0x7E,
    0x4F,
    0x1C,
    0x2D,
    0xBA,
    0x8B,
    0xD8,
    0xE9,
    0xC7,
    0xF6,
    0xA5,
    0x94,
    0x03,
    0x32,
    0x61,
    0x50,
    0xBB,
    0x8A,
    0xD9,
    0xE8,
    0x7F,
    0x4E,
    0x1D,
    0x2C,
    0x02,
    0x33,
    0x60,
    0x51,
    0xC6,
    0xF7,
    0xA4,
    0x95,
    0xF8,
    0xC9,
    0x9A,
    0xAB,
    0x3C,
    0x0D,
    0x5E,
    0x6F,
    0x41,
    0x70,
    0x23,
    0x12,
    0x85,
    0xB4,
    0xE7,
    0xD6,
    0x7A,
    0x4B,
    0x18,
    0x29,
    0xBE,
    0x8F,
    0xDC,
    0xED,
    0xC3,
    0xF2,
    0xA1,
    0x90,
    0x07,
    0x36,
    0x65,
    0x54,
    0x39,
    0x08,
    0x5B,
    0x6A,
    0xFD,
    0xCC,
    0x9F,
    0xAE,
    0x80,
    0xB1,
    0xE2,
    0xD3,
    0x44,
    0x75,
    0x26,
    0x17,
    0xFC,
    0xCD,
    0x9E,
    0xAF,
    0x38,
    0x09,
    0x5A,
    0x6B,
    0x45,
    0x74,
    0x27,
    0x16,
    0x81,
    0xB0,
    0xE3,
    0xD2,
    0xBF,
    0x8E,
    0xDD,
    0xEC,
    0x7B,
    0x4A,
    0x19,
    0x28,
    0x06,
    0x37,
    0x64,
    0x55,
    0xC2,
    0xF3,
    0xA0,
    0x91,
    0x47,
    0x76,
    0x25,
    0x14,
    0x83,
    0xB2,
    0xE1,
    0xD0,
    0xFE,
    0xCF,
    0x9C,
    0xAD,
    0x3A,
    0x0B,
    0x58,
    0x69,
    0x04,
    0x35,
    0x66,
    0x57,
    0xC0,
    0xF1,
    0xA2,
    0x93,
    0xBD,
    0x8C,
    0xDF,
    0xEE,
    0x79,
    0x48,
    0x1B,
    0x2A,
    0xC1,
    0xF0,
    0xA3,
    0x92,
    0x05,
    0x34,
    0x67,
    0x56,
    0x78,
    0x49,
    0x1A,
    0x2B,
    0xBC,
    0x8D,
    0xDE,
    0xEF,
    0x82,
    0xB3,
    0xE0,
    0xD1,
    0x46,
    0x77,
    0x24,
    0x15,
    0x3B,
    0x0A,
    0x59,
    0x68,
    0xFF,
    0xCE,
    0x9D,
    0xAC,
};

// CRC8 校验函数 (查表法, 多项式 0x31)
static uint8_t checksum_update(uint8_t current, uint8_t byte)
{
    return CRC8_TABLE[current ^ byte];
}

uint8_t calculate_checksum(const uint8_t *data, size_t len)
{
    uint8_t cs = 0;
    for (size_t i = 0; i < len; i++)
    {
        cs = checksum_update(cs, data[i]);
    }
    return cs;
}

/* USER CODE BEGIN Private_Variables */
/* USER CODE END Private_Variables */

// 用户需要实现的回调函数
__attribute__((weak)) void on_receive_FruitDetection(const Packet_FruitDetection *pkt)
{
    (void)pkt;
    /* USER CODE BEGIN on_receive_FruitDetection */
    /* USER CODE END on_receive_FruitDetection */
}
__attribute__((weak)) void on_receive_Ack(const Packet_Ack *pkt)
{
    (void)pkt;
    /* USER CODE BEGIN on_receive_Ack */
    /* USER CODE END on_receive_Ack */
}
__attribute__((weak)) void on_receive_Heartbeat(const Packet_Heartbeat *pkt)
{
    (void)pkt;
    // Default system behavior: ack the latest heartbeat with the same count.
    send_Heartbeat(pkt);
    /* USER CODE BEGIN on_receive_Heartbeat */
    /* USER CODE END on_receive_Heartbeat */
}
__attribute__((weak)) void on_receive_Handshake(const Packet_Handshake *pkt)
{
    (void)pkt;
    // Default system behavior: ack matching protocol hash automatically.
    if (pkt->protocol_hash == PROTOCOL_HASH)
    {
        send_Handshake(pkt);
    }
    /* USER CODE BEGIN on_receive_Handshake */
    /* USER CODE END on_receive_Handshake */
}

/* USER CODE BEGIN Code_0 */
/* USER CODE END Code_0 */

/**
 * @brief 协议解析状态机，在串口中断或轮询中调用此函数处理每个接收到的字节
 * @param byte 接收到的单个字节
 */
void protocol_fsm_feed(uint8_t byte)
{
    switch (rx_state)
    {
    case STATE_WAIT_HEADER1:
        if (byte == FRAME_HEADER1)
        {
            rx_state = STATE_WAIT_HEADER2;
        }
        break;

    case STATE_WAIT_HEADER2:
        if (byte == FRAME_HEADER2)
        {
            rx_state = STATE_WAIT_ID;
        }
        else if (byte != FRAME_HEADER1)
        {
            // 若该字节是新的 HEADER1，则停留在本状态继续等待 HEADER2
            rx_state = STATE_WAIT_HEADER1;
        }
        break;

    case STATE_WAIT_ID:
        rx_id = byte;
        rx_checksum = checksum_update(0, rx_id); // 校验包含 ID
        rx_state = STATE_WAIT_LEN;
        break;

    case STATE_WAIT_LEN:
        if (byte > sizeof(rx_buffer))
        {
            // 超出协议内最大 payload，直接放弃当前候选帧并重新解析该字节
            rx_state = STATE_WAIT_HEADER1;
            protocol_fsm_feed(byte);
            return;
        }
        rx_data_len = byte;
        rx_checksum = checksum_update(rx_checksum, rx_data_len); // 校验包含 Len
        rx_cnt = 0;
        rx_state = (rx_data_len > 0) ? STATE_WAIT_DATA : STATE_WAIT_CRC;
        break;

    case STATE_WAIT_DATA:
        rx_buffer[rx_cnt++] = byte;
        rx_checksum = checksum_update(rx_checksum, byte);
        if (rx_cnt >= rx_data_len)
        {
            rx_state = STATE_WAIT_CRC;
        }
        break;

    case STATE_WAIT_CRC:
        if (byte == rx_checksum)
        {
            // 校验通过，分发数据
            switch (rx_id)
            {
            case PACKET_ID_FRUITDETECTION:
                if (rx_data_len == sizeof(Packet_FruitDetection))
                {
                    on_receive_FruitDetection((Packet_FruitDetection *)rx_buffer);
                }
                break;
            case PACKET_ID_ACK:
                if (rx_data_len == sizeof(Packet_Ack))
                {
                    on_receive_Ack((Packet_Ack *)rx_buffer);
                }
                break;
            case PACKET_ID_HEARTBEAT:
                if (rx_data_len == sizeof(Packet_Heartbeat))
                {
                    on_receive_Heartbeat((Packet_Heartbeat *)rx_buffer);
                }
                break;
            case PACKET_ID_HANDSHAKE:
                if (rx_data_len == sizeof(Packet_Handshake))
                {
                    on_receive_Handshake((Packet_Handshake *)rx_buffer);
                }
                break;

            default:
                break;
            }
        }
        rx_state = STATE_WAIT_HEADER1;
        break;

    default:
        rx_state = STATE_WAIT_HEADER1;
        break;
    }
}

// --- 发送函数 ---
// 外部依赖：用户必须实现 void serial_write(const uint8_t* data, uint16_t len);
extern void serial_write(const uint8_t *data, uint16_t len);

void send_FruitDetection(const Packet_FruitDetection *pkt)
{
    uint8_t buffer[4 + sizeof(Packet_FruitDetection) + 1];
    uint16_t idx = 0;

    buffer[idx++] = FRAME_HEADER1;
    buffer[idx++] = FRAME_HEADER2;
    buffer[idx++] = PACKET_ID_FRUITDETECTION;
    buffer[idx++] = sizeof(Packet_FruitDetection);

    memcpy(&buffer[idx], pkt, sizeof(Packet_FruitDetection));
    idx += sizeof(Packet_FruitDetection);

    buffer[idx] = calculate_checksum(&buffer[2], idx - 2);
    idx++;

    serial_write(buffer, idx);
}
void send_Ack(const Packet_Ack *pkt)
{
    uint8_t buffer[4 + sizeof(Packet_Ack) + 1];
    uint16_t idx = 0;

    buffer[idx++] = FRAME_HEADER1;
    buffer[idx++] = FRAME_HEADER2;
    buffer[idx++] = PACKET_ID_ACK;
    buffer[idx++] = sizeof(Packet_Ack);

    memcpy(&buffer[idx], pkt, sizeof(Packet_Ack));
    idx += sizeof(Packet_Ack);

    buffer[idx] = calculate_checksum(&buffer[2], idx - 2);
    idx++;

    serial_write(buffer, idx);
}
void send_Heartbeat(const Packet_Heartbeat *pkt)
{
    uint8_t buffer[4 + sizeof(Packet_Heartbeat) + 1];
    uint16_t idx = 0;

    buffer[idx++] = FRAME_HEADER1;
    buffer[idx++] = FRAME_HEADER2;
    buffer[idx++] = PACKET_ID_HEARTBEAT;
    buffer[idx++] = sizeof(Packet_Heartbeat);

    memcpy(&buffer[idx], pkt, sizeof(Packet_Heartbeat));
    idx += sizeof(Packet_Heartbeat);

    buffer[idx] = calculate_checksum(&buffer[2], idx - 2);
    idx++;

    serial_write(buffer, idx);
}
void send_Handshake(const Packet_Handshake *pkt)
{
    uint8_t buffer[4 + sizeof(Packet_Handshake) + 1];
    uint16_t idx = 0;

    buffer[idx++] = FRAME_HEADER1;
    buffer[idx++] = FRAME_HEADER2;
    buffer[idx++] = PACKET_ID_HANDSHAKE;
    buffer[idx++] = sizeof(Packet_Handshake);

    memcpy(&buffer[idx], pkt, sizeof(Packet_Handshake));
    idx += sizeof(Packet_Handshake);

    buffer[idx] = calculate_checksum(&buffer[2], idx - 2);
    idx++;

    serial_write(buffer, idx);
}

/* USER CODE BEGIN Code_1 */
/* USER CODE END Code_1 */

/*
// --- 建议的消息发送模板 (以 Heartbeat 为例) ---
// 建议在定时器回调或主循环中以固定频率调用

void heartbeat_timer_callback(void) {
    static uint32_t hb_count = 0;
    Packet_Heartbeat pkt;
    pkt.count = hb_count++;
    send_Heartbeat(&pkt);
}
*/
