// Auto-generated by scripts/codegen.py from config/protocol.yaml.
//
// 警告：本文件生成在 build 目录中，清理构建目录（rm -rf build、
// colcon build --cmake-clean-first 等）会连同 USER CODE 块中的手写代码一起丢失。
// 长期维护的 MCU 业务代码请保存在你的 MCU 工程里，本文件只做集成拷贝。
#pragma once
#include <stdint.h>
#include <stddef.h>

/* USER CODE BEGIN Includes */
/* USER CODE END Includes */

// 协议哈希校验码
#define PROTOCOL_HASH 0x0EBAB184

// 校验算法: CRC8
#define CHECKSUM_ALGO_CRC8 1

// 握手配置
#define CFG_REQUIRE_HANDSHAKE 1
#define CFG_IGNORE_VERSION_MISMATCH 0

// 心跳配置
#define CFG_ENABLE_HEARTBEAT 1
#define CFG_STRICT_HEARTBEAT 1
#define CFG_HEARTBEAT_TIMEOUT_MS 3000

// 可靠传输配置
#define CFG_RELIABLE_RETRY_INTERVAL_MS 100
#define CFG_RELIABLE_MAX_RETRIES 3

/* USER CODE BEGIN Private_Defines */
/* USER CODE END Private_Defines */

// 帧头定义
#define FRAME_HEADER1 90
#define FRAME_HEADER2 165

// 数据包ID定义
typedef enum
{
    PACKET_ID_FRUITDETECTION = 16,
    PACKET_ID_ACK = 253,
    PACKET_ID_HEARTBEAT = 254,
    PACKET_ID_HANDSHAKE = 255,
} PacketID;

#pragma pack(1)
typedef struct
{
    uint8_t fruit_id;
    uint8_t status;
} Packet_FruitDetection;

typedef struct
{
    uint8_t acked_id;
    uint8_t ack_seq;
} Packet_Ack;

typedef struct
{
    uint32_t count;
} Packet_Heartbeat;

typedef struct
{
    uint32_t protocol_hash;
} Packet_Handshake;

#pragma pack()

// 协议辅助函数声明
uint8_t calculate_checksum(const uint8_t *data, size_t len);
void protocol_fsm_feed(uint8_t byte);

// 用户可覆盖的接收回调与自动生成的发送函数声明
void on_receive_FruitDetection(const Packet_FruitDetection *pkt);
void send_FruitDetection(const Packet_FruitDetection *pkt);
void on_receive_Ack(const Packet_Ack *pkt);
void send_Ack(const Packet_Ack *pkt);
void on_receive_Heartbeat(const Packet_Heartbeat *pkt);
void send_Heartbeat(const Packet_Heartbeat *pkt);
void on_receive_Handshake(const Packet_Handshake *pkt);
void send_Handshake(const Packet_Handshake *pkt);

/* USER CODE BEGIN User_Types */
/* USER CODE END User_Types */
